In [1]:
from google.colab import drive
drive.mount('/content/drive')

root = '/content/drive/MyDrive/Colab Notebooks/FINAL PROJECT ZENIUS/Dataset/'

Mounted at /content/drive


In [2]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [3]:
# import libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import BaggingRegressor

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, roc_curve, auc, classification_report, roc_auc_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Import Data Train dan Test

In [4]:
# tabel setting
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [5]:
# load data
X_train = pd.read_csv(root+'X_train_2.csv')
X_test = pd.read_csv(root+'X_test_2.csv')
y_train = pd.read_csv(root+'y_train_2.csv')
y_test = pd.read_csv(root+'y_test_2.csv')

# Import Model

In [6]:
# Load Model 3
LR_Model = pickle.load(open(root + "Model/LR_Model_3.pkl", 'rb'))
RF_Model = pickle.load(open(root + "Model/RF_Model_3.pkl", 'rb'))
KNN_Model = pickle.load(open(root + "Model/KNN_Model_3.pkl", 'rb'))

In [21]:
# Ensemble Model
ens_model_3_hard = pickle.load(open(root + "Model/Ensemble_Model_3_Hard.pkl", 'rb'))
ens_model_3_soft = pickle.load(open(root + "Model/Ensemble_Model_3_Soft.pkl", 'rb'))

# Evaluasi Model

## Logistik Regression Model

### Model 3

In [7]:
y_pred_lr = LR_Model.predict(X_test.values)

In [8]:
print("Accuracy Logit : ", accuracy_score(y_test, y_pred_lr))
print("Precision Logit : ", precision_score(y_test, y_pred_lr, average='macro'))
print("Recall Logit : ",recall_score(y_test, y_pred_lr, average='macro'))

Accuracy Logit :  0.8789350736030257
Precision Logit :  0.9352363124738323
Recall Logit :  0.5619655451815169


In [9]:
score = roc_auc_score(y_test, y_pred_lr)

print(f"ROC AUC LR: {score}")

ROC AUC LR: 0.5619655451815169


In [10]:
f1_lr = f1_score(y_test, y_pred_lr)
print(f"F1 Score LR : {f1_lr}")

F1 Score LR : 0.22057770350919073


In [11]:
# Confusion Matrix Logit Model
print("Cofusion Matrix Logit 2 : \n", confusion_matrix(y_test, y_pred_lr))

Cofusion Matrix Logit 2 : 
 [[46484     6]
 [ 6524   924]]


## KNN Model

### Model 3

In [12]:
y_pred_knn = KNN_Model.predict(X_test.values)

In [13]:
print("Accuracy KNN : ", accuracy_score(y_test, y_pred_knn))
print("Precision KNN : ", precision_score(y_test, y_pred_knn, average='macro'))
print("Recall KNN : ",recall_score(y_test, y_pred_knn, average='macro'))

Accuracy KNN :  0.8712781341540287
Precision KNN :  0.7615501778589422
Recall KNN :  0.5690246611828098


In [14]:
score = roc_auc_score(y_test, y_pred_knn)

print(f"ROC AUC KNN : {score}")

ROC AUC KNN : 0.5690246611828098


In [15]:
# Confusion Matrix KNN Model 3
print("Cofusion Matrix KNN : \n", confusion_matrix(y_test, y_pred_knn))

Cofusion Matrix KNN : 
 [[45867   623]
 [ 6320  1128]]


## Random Forest

### Model 3

In [16]:
y_pred_rf = RF_Model.predict(X_test.values)

In [17]:
print("Accuracy RF : ", accuracy_score(y_test, y_pred_rf))
print("Precision RF : ", precision_score(y_test, y_pred_rf, average='macro'))
print("Recall RF : ",recall_score(y_test, y_pred_rf, average='macro'))

Accuracy RF :  0.9058919500166859
Precision RF :  0.9495698684874112
Recall RF :  0.659575641851764


In [18]:
score = roc_auc_score(y_test, y_pred_rf)

print(f"ROC AUC RF: {score}")

ROC AUC RF: 0.659575641851764


In [19]:
f1_rf = f1_score(y_test, y_pred_rf)
print(f"F1 Score RF: {f1_rf}")

F1 Score RF: 0.483726606997559


In [20]:
# Confusion Matrix RF Model 3
print("Cofusion Matrix KNN 2 : \n", confusion_matrix(y_test, y_pred_rf))

Cofusion Matrix KNN 2 : 
 [[46484     6]
 [ 5070  2378]]


## Ensemble Model

### Model 3

#### Hard Vote

In [23]:
y_pred_ens_3_hard = ens_model_3_hard.predict(X_test.values)

In [24]:
print("Accuracy Ensemble 2 Hard : ", accuracy_score(y_test, y_pred_ens_3_hard))
print("Precision Ensemble 2 Hard : ", precision_score(y_test, y_pred_ens_3_hard, average='macro'))
print("Recall Ensemble 2 Hard : ",recall_score(y_test, y_pred_ens_3_hard, average='macro'))

Accuracy Ensemble 2 Hard :  0.8800660017056621
Precision Ensemble 2 Hard :  0.9384219020078164
Recall Ensemble 2 Hard :  0.565778718683135


In [25]:
score = roc_auc_score(y_test, y_pred_ens_3_hard)

print(f"ROC AUC ENS 2 HARD : {score}")

ROC AUC ENS 2 HARD : 0.565778718683135


In [27]:
f1_ens_3_hard = f1_score(y_test, y_pred_ens_3_hard)
print(f"F1 Score ENS 2 HARD: {f1_ens_3_hard}")

F1 Score ENS 2 HARD: 0.23253054929410366


In [28]:
# Confusion Matrix Ens Model 3
print("Cofusion Matrix ENS 2 HARD : \n", confusion_matrix(y_test, y_pred_ens_3_hard))

Cofusion Matrix ENS 2 HARD : 
 [[46489     1]
 [ 6468   980]]


#### Soft Vote

In [26]:
y_pred_ens_3_soft = ens_model_3_soft.predict(X_test.values)

In [29]:
print("Accuracy Ensemble 2 Soft : ", accuracy_score(y_test, y_pred_ens_3_soft))
print("Precision Ensemble 2 Soft : ", precision_score(y_test, y_pred_ens_3_soft, average='macro'))
print("Recall Ensemble 2 Soft : ",recall_score(y_test, y_pred_ens_3_soft, average='macro'))

Accuracy Ensemble 2 Soft :  0.8831250695242686
Precision Ensemble 2 Soft :  0.9398671548944297
Recall Ensemble 2 Soft :  0.5768555178238439


In [30]:
score = roc_auc_score(y_test, y_pred_ens_3_soft)

print(f"ROC AUC ENS 2 SOFT : {score}")

ROC AUC ENS 2 SOFT : 0.5768555178238439


In [31]:
f1_ens_3_soft = f1_score(y_test, y_pred_ens_3_soft)
print(f"F1 Score ENS 2 SOFT : {f1_ens_3_soft}")

F1 Score ENS 2 SOFT : 0.2664649755643472


In [32]:
# Confusion Matrix RF Model 2
print("Cofusion Matrix ENS 2 SOFT : \n", confusion_matrix(y_test, y_pred_ens_3_soft))

Cofusion Matrix ENS 2 SOFT : 
 [[46489     1]
 [ 6303  1145]]
