In [ ]:
from google.colab import drive
drive.mount('/content/drive')

root = '/content/drive/MyDrive/Colab Notebooks/FINAL PROJECT ZENIUS/Dataset/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [ ]:
# import libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import BaggingRegressor

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, roc_curve, auc, classification_report, roc_auc_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Import Data Train dan Test

In [ ]:
# tabel setting
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [ ]:
# load data
X_train = pd.read_csv(root+'X_train.csv')
X_test = pd.read_csv(root+'X_test.csv')
y_train = pd.read_csv(root+'y_train.csv')
y_test = pd.read_csv(root+'y_test.csv')

# Import Model

In [ ]:
# Load Model
LR_Model = pickle.load(open(root + "Model/LR_Model.pkl", 'rb'))
RF_Model = pickle.load(open(root + "Model/RF_Model.pkl", 'rb'))
# KNN_Model = pickle.load(open(root + "Model/KNN_Model.pkl", 'rb'))

In [ ]:
# Load Model 2
LR_Model_2 = pickle.load(open(root + "Model/LR_Model_2.pkl", 'rb'))
RF_Model_2 = pickle.load(open(root + "Model/RF_Model_2.pkl", 'rb'))
KNN_Model_2 = pickle.load(open(root + "Model/KNN_Model_2.pkl", 'rb'))

In [ ]:
# Ensemble Model 2
ens_model_2_hard = pickle.load(open(root + "Model/Ensemble_Model_2_Hard.pkl", 'rb'))
ens_model_2_soft = pickle.load(open(root + "Model/Ensemble_Model_2_Soft.pkl", 'rb'))

# Evaluasi Model

## Logistik Regression Model

### Model 1

In [ ]:
y_pred_lr = LR_Model.predict(X_test.values)

In [ ]:
print("Accuracy Logit : ", accuracy_score(y_test, y_pred_lr))
print("Precision Logit : ", precision_score(y_test, y_pred_lr, average='macro'))
print("Recall Logit : ",recall_score(y_test, y_pred_lr, average='macro'))

Accuracy Logit :  0.8789350736030257
Precision Logit :  0.9352363124738323
Recall Logit :  0.5619655451815169


In [ ]:
score = roc_auc_score(y_test, y_pred_lr)

print(f"ROC AUC LR: {score}")

ROC AUC LR: 0.5619655451815169


In [ ]:
f1_lr = f1_score(y_test, y_pred_lr)
print(f"F1 Score LR : {f1_lr}")

F1 Score LR : 0.22057770350919073


In [ ]:
# Confusion Matrix Logit Model
print("Cofusion Matrix Logit 2 : \n", confusion_matrix(y_test, y_pred_lr))

Cofusion Matrix Logit 2 : 
 [[46484     6]
 [ 6524   924]]


### Model 2

In [ ]:
y_pred_lr_2 = LR_Model_2.predict(X_test.values)

In [ ]:
print("Accuracy Logit 2 : ", accuracy_score(y_test, y_pred_lr_2))
print("Precision Logit 2 : ", precision_score(y_test, y_pred_lr_2, average='macro'))
print("Recall Logit 2 : ",recall_score(y_test, y_pred_lr_2, average='macro'))

Accuracy Logit 2 :  0.8789350736030257
Precision Logit 2 :  0.9352363124738323
Recall Logit 2 :  0.5619655451815169


In [ ]:
score = roc_auc_score(y_test, y_pred_lr_2)

print(f"ROC AUC LR 2: {score}")

ROC AUC LR 2: 0.5619655451815169


In [ ]:
f1_lr_2 = f1_score(y_test, y_pred_lr_2)
print(f"F1 Score LR 2 : {f1_lr_2}")

F1 Score LR 2 : 0.22057770350919073


In [ ]:
# Confusion Matrix Logit Model 2
print("Cofusion Matrix Logit 2 : \n", confusion_matrix(y_test, y_pred_lr_2))

Cofusion Matrix Logit 2 : 
 [[46484     6]
 [ 6524   924]]


## KNN Model

### Model 1

In [ ]:
# y_pred_knn = KNN_Model.predict(X_test.values)

In [ ]:
# print("Accuracy KNN : ", accuracy_score(y_test, y_pred_knn))
# print("Precision KNN : ", precision_score(y_test, y_pred_knn, average='macro'))
# print("Recall KNN : ",recall_score(y_test, y_pred_knn, average='macro'))

In [ ]:
# score = roc_auc_score(y_test, y_pred_knn_2)

# print(f"ROC AUC KNN: {score}")

In [ ]:
# Confusion Matrix KNN Model
# print("Cofusion Matrix KNN : \n", confusion_matrix(y_test, y_pred_knn))

### Model 2

In [ ]:
y_pred_knn_2 = KNN_Model_2.predict(X_test.values)

In [ ]:
print("Accuracy KNN 2 : ", accuracy_score(y_test, y_pred_knn_2))
print("Precision KNN 2 : ", precision_score(y_test, y_pred_knn_2, average='macro'))
print("Recall KNN 2 : ",recall_score(y_test, y_pred_knn_2, average='macro'))

Accuracy KNN 2 :  0.8712781341540287
Precision KNN 2 :  0.7615501778589422
Recall KNN 2 :  0.5690246611828098


In [ ]:
score = roc_auc_score(y_test, y_pred_knn_2)

print(f"ROC AUC KNN 2: {score}")

ROC AUC KNN 2: 0.5690246611828098


In [ ]:
f1_knn_2 = f1_score(y_test, y_pred_knn_2)
print(f"F1 Score KNN 2: {f1_knn_2}")

F1 Score KNN 2: 0.24524404826611587


In [ ]:
# Confusion Matrix KNN Model 2
print("Cofusion Matrix KNN 2 : \n", confusion_matrix(y_test, y_pred_knn_2))

Cofusion Matrix KNN 2 : 
 [[45867   623]
 [ 6320  1128]]


## Random Forest

### Model 1

In [ ]:
y_pred_rf = RF_Model.predict(X_test.values)

In [ ]:
print("Accuracy RF : ", accuracy_score(y_test, y_pred_rf))
print("Precision RF : ", precision_score(y_test, y_pred_rf, average='macro'))
print("Recall RF : ",recall_score(y_test, y_pred_rf, average='macro'))

Accuracy RF :  0.905465534502577
Precision RF :  0.9493565695277184
Recall RF :  0.6580316031836652


In [ ]:
score = roc_auc_score(y_test, y_pred_rf)

print(f"ROC AUC RF: {score}")

ROC AUC RF: 0.6580316031836652


In [ ]:
f1_rf = f1_score(y_test, y_pred_rf)
print(f"F1 Score RF: {f1_rf}")

F1 Score RF: 0.4801712712814762


In [ ]:
# Confusion Matrix RF Model
print("Cofusion Matrix KNN 2 : \n", confusion_matrix(y_test, y_pred_rf))

Cofusion Matrix KNN 2 : 
 [[46484     6]
 [ 5093  2355]]


### Model 2

In [ ]:
y_pred_rf_2 = RF_Model_2.predict(X_test.values)

In [ ]:
print("Accuracy RF 2 : ", accuracy_score(y_test, y_pred_rf_2))
print("Precision RF 2 : ", precision_score(y_test, y_pred_rf_2, average='macro'))
print("Recall RF 2 : ",recall_score(y_test, y_pred_rf_2, average='macro'))

Accuracy RF 2 :  0.8995327969149765
Precision RF 2 :  0.9364420761771017
Recall RF 2 :  0.6390299191191573


In [ ]:
score = roc_auc_score(y_test, y_pred_rf_2)

print(f"ROC AUC RF 2: {score}")

ROC AUC RF 2: 0.6390299191191574


In [ ]:
f1_rf_2 = f1_score(y_test, y_pred_rf_2)
print(f"F1 Score RF 2: {f1_rf_2}")

F1 Score RF 2: 0.4341651874282134


In [ ]:
# Confusion Matrix RF Model 2
print("Cofusion Matrix KNN 2 : \n", confusion_matrix(y_test, y_pred_rf_2))

Cofusion Matrix KNN 2 : 
 [[46440    50]
 [ 5369  2079]]


## Ensemble Model

### Model 1

### Model 2

#### Hard Vote

In [ ]:
y_pred_ens_2_hard = ens_model_2_hard.predict(X_test.values)

In [ ]:
print("Accuracy Ensemble 2 Hard : ", accuracy_score(y_test, y_pred_ens_2_hard))
print("Precision Ensemble 2 Hard : ", precision_score(y_test, y_pred_ens_2_hard, average='macro'))
print("Recall Ensemble 2 Hard : ",recall_score(y_test, y_pred_ens_2_hard, average='macro'))

Accuracy Ensemble 2 Hard :  0.8798249842411657
Precision Ensemble 2 Hard :  0.9378000644621844
Recall Ensemble 2 Hard :  0.564962378290008


In [ ]:
score = roc_auc_score(y_test, y_pred_ens_2_hard)

print(f"ROC AUC ENS 2 HARD : {score}")

ROC AUC ENS 2 HARD : 0.564962378290008


In [ ]:
f1_ens_2_hard = f1_score(y_test, y_pred_ens_2_hard)
print(f"F1 Score ENS 2 HARD: {f1_ens_2_hard}")

F1 Score ENS 2 HARD: 0.22998336897125207


In [ ]:
# Confusion Matrix RF Model 2
print("Cofusion Matrix ENS 2 HARD : \n", confusion_matrix(y_test, y_pred_ens_2_hard))

Cofusion Matrix ENS 2 HARD : 
 [[46488     2]
 [ 6480   968]]


#### Soft Vote

In [ ]:
y_pred_ens_2_soft = ens_model_2_soft.predict(X_test.values)

In [ ]:
print("Accuracy Ensemble 2 Soft : ", accuracy_score(y_test, y_pred_ens_2_soft))
print("Precision Ensemble 2 Soft : ", precision_score(y_test, y_pred_ens_2_soft, average='macro'))
print("Recall Ensemble 2 Soft : ",recall_score(y_test, y_pred_ens_2_soft, average='macro'))

Accuracy Ensemble 2 Soft :  0.8796766658014757
Precision Ensemble 2 Soft :  0.9382367641599658
Recall Ensemble 2 Soft :  0.5643689442470448


In [ ]:
score = roc_auc_score(y_test, y_pred_ens_2_soft)

print(f"ROC AUC ENS 2 SOFT : {score}")

ROC AUC ENS 2 SOFT : 0.5643689442470448


In [ ]:
f1_ens_2_soft = f1_score(y_test, y_pred_ens_2_soft)
print(f"F1 Score ENS 2 SOFT : {f1_ens_2_soft}")

F1 Score ENS 2 SOFT : 0.228116079923882


In [ ]:
# Confusion Matrix RF Model 2
print("Cofusion Matrix ENS 2 SOFT : \n", confusion_matrix(y_test, y_pred_ens_2_soft))

Cofusion Matrix ENS 2 SOFT : 
 [[46489     1]
 [ 6489   959]]
